# Usar una imagen base ligera de Node.js
FROM node:20-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar y instalar dependencias en una sola capa
COPY package*.json ./
RUN npm install --production && npm cache clean --force

# Copiar el resto del código fuente
COPY . .

# Construir el proyecto
RUN npm run build

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]