services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=1433
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=db_p@ssword123
      - DATABASE_NAME=db_user_system
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=pruebaTecnic@123
      - ACCEPT_EULA=Y
    volumes:
      - db_data:/var/opt/mssql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  db_data:
