x-common: &common-variables
  environment:
    DATABASE_USER: user
    DATABASE_HOST: db
    DATABASE_PASSWORD: root
    DATABASE_NAME: user_system
    DATABASE_PORT: 3306
    JWT_SECRET: your_jwt_secret_key
    JWT_EXPIRES_IN: 1h

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4002:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    <<: *common-variables
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_system
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge